version: 2

sphinx:
    configuration: doc/conf.py
    fail_on_warning: true

formats: all

python:
    version: 3.7
    install:
        - method: setuptools

conda:
    environment: doc/environment.yml
