version: 2

sphinx:
    configuration: doc/conf.py
    fail_on_warning: false

formats: all

python:
    version: 3.8
    install:
        - method: setuptools
          path: .

conda:
    environment: doc/environment.yml
