dependencies:
    - python=3.7
    - numpy
    - scipy
    - h5py
    - sphinx
    - opencv
    - matplotlib
    - pip:
        - pyvisa
        - pyvisa-py
        - pydaqmx
        - sphinx-argparse
        - sphinx_rtd_theme
