channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy
    - scipy
    - h5py
    - sphinx
    - opencv
    - matplotlib
    - aiohttp
    - pip:
        - aiohttp_jinja2
        - pyvisa
        - pyvisa-py
        - pydaqmx
        - sphinx-argparse
        - sphinx_rtd_theme
